### ISSUE TITLE
Set up automation tools

### ISSUE THREAD

**Issue by aalbaali** [aalbaali/turtle_nav_cpp#24]
Epic: #23

### Description
Setup automation tools for this repo. Note that many of the CI tools are already set up.

### Tasks
- [x] Setup Docker-based CI unit testing #8
- [x] Add pre-commit hooks #13
- [ ] Add code coverage tool (e.g., [Codecov](https://about.codecov.io/))
- [ ] Look into using [ROS2 CI tools](https://ubuntu.com/blog/ros-2-ci-with-github-actions) #22
