### ISSUE TITLE
Create dead-reckoning estimation

### ISSUE THREAD

**Issue by aalbaali** [aalbaali/turtle_nav_cpp#31]
### Description
Create a dead-reckoning solution. This epic involves writing a dead-reckoning estimator node, visualizing the results in RVIZ, and using SE(2) kinematics to estimate uncertainty bounds on the robot pose (i.e., visualizing the banana curve)

### Stories
- [ ] Create a dead-reckoning estimator node (without uncertainty calculations) #<story number>
- [ ] Visualize results in RVIZ (this may be more of a validation task. Maybe plot results and use them in the wiki) #<story number>
- [ ] Use $SE(2)$ kinematics to estimate the uncertainty bounds on the pose in the Lie algebra (Possibly use point cloud registration)
